const ProjectCardData = [
  {
    id: 1,
    img: "/ems.png",
    heading: "",
    para: "",
    stack: "",
    link: "",
    but: "",
    demoLink: "",
  },
  {
    id: 2,
    img: "",
    heading: "Employee Management Full Stack",
    para: "The Employee Management System is a full-stack responsive web application.This system enables organizations to efficiently manage employee data, including adding, updating, deleting, and viewing employee details",
    stack: "React, SpringBoot, TailwindCss, Sql",
    link: "https://github.com/Shefali1403/emsFullStackk",
    but: "Demo",
    demoLink: "https://github.com/Shefali1403/emsFullStackk",
  },
  {
    id: 3,
    img: "",
    heading: "E-commerce React Website",
    para: "Shefmart is a user-friendly ecommerce React app with its sleek design and intuitive interface, Shefmart offers an exceptional shopping experience for customers.",
    stack: "React, Bootstrap, Context Api",
    link: "https://github.com/Shefali1403/e-commerce",
    but: "Demo",
    demoLink: "https://shefmart.onrender.com/",
  },
  {
    id: 4,
    img: "/shefmart.png",
    heading: "",
    para: "",
    stack: "",
    link: "",
    but: "",
    demoLink: "",
  },
  {
    id: 5,
    img: "/spotify.png",
    heading: "",
    para: "",
    stack: "",
    link: "",
    but: "",
    demoLink: "",
  },
  {
    id: 6,
    img: "",
    heading: "SpotifyClone",
    para: "Developing a dynamic Spotify web application using ReactJS, JavaScript, and Tailwind CSS. This application fetches songs dynamically via a REST API, ensuring a seamless and interactive user experience.",
    stack: "React, Css, Javascript",
    link: "https://github.com/Shefali1403/spotifyapp",
    but: "Demo",
    demoLink: "https://spotifyapp-xcda.onrender.com/",
  },
];
export default ProjectCardData;
